[theme]
theme = "slick"
[icons]
icons = "awesome5"

[[block]]
block = "music"
player = "mpd"

[[block]]
block = "nvidia_gpu"
format = "$icon RTX 3090 $utilization $temperature $clocks "

[[block]]
block = "net"

[[block]]
block = "disk_space"
path = "/home"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = "$icon $path $available"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = "$icon $path $available"

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:1)"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "notify"

[[block]]
block = "time"
interval = 60
format = "$timestamp.datetime(f:'%B %d %Y %R')"
