theme = "slick"
icons = "awesome"

[[block]]
block = "net"

[[block]]
block = "disk_space"
path = "/home"
alias = "/home"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = "{icon} {path} {available}"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = "{icon} {path} {available}"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"


[[block]]
block = "time"
interval = 5
timezone = "US/Pacific"
format = "SFO: %R" # month/day/year w/ 24H

[[block]]
block = "time"
interval = 5
timezone = "US/Eastern"
format = "NYC: %R"

[[block]]
block = "time"
interval = 5
timezone = "Europe/Dublin"
format = "DUB: %R" # month/day/year w/ 24H

[[block]]
block = "time"
interval = 60
format = "%D"

[[block]]
block = "sound"

[[block]]
block = "notify"

[[block]]
block = "battery"
driver = "upower"
interval = 10
format = "{percentage} {time}"
