keys:
  - &admin_prismo age10z957w97h03pxd3qhutghn74czzrymta0ekrlq3jd79f7nds4aysh9xr2h
  - &server_prismo age14lpfe6ncu46e7js70z0pvgrng89fvxwgxtak7snfqnzxcwqfwpcqrzsw8f
  
creation_rules:
  - path: secrets/prismo.yml
    key_groups:
    - age:
      - *admin_prismo
      - *server_prismo

